-- BUSCA TODOS OS CLIENTE
SELECT CLI.ID, MOVI.TIPO, COUNT(CONT.ID) FROM CLIENTE CLI
-- JUNTA MEU CLIENTE COM A TABELA CONTEINER
    JOIN CONTEINER CONT ON CONT.CLIENTE = CLI.ID
-- JUNTA MEU CONETINER COM A TABELA MOVIMENTO
    JOIN MOVIMENTO MOVI ON MOVI.CONTEINER = CONT.ID
-- AGRUPA POR ID DO CLIENTE E TIPO DE MOVIMENTO
    GROUP BY CLI.ID, MOVI.TIPO;






